### ISSUE TITLE
Why use the letter z?

### ISSUE THREAD

**Issue by okwolf** [staltz/zii#1]
Wouldn't `D` look more like the pipeline operator `|>`?

```js
'hello'
  .D(doubleSay)
  .D(capitalize)
  .D(exclaim)
  .D(console.log) // Hello, hello!
```

**Comment by staltz** [comment]
I chose z because it kind of looks like the sharp part of `|>` and because z is usually cool and it's the last letter of the alphabet and easier to remember.

But nothing stops you from publishing your own fork:  :)

```
Object.defineProperty(Object.prototype, 'D', {
  value: function(f) {
    return f(this.valueOf());
  },
  writable: true,
  configurable: true,
});
```
